---
- hosts: "{{ target + '_drbd_nodes' }}"
  tasks:
    - name: Set fact for Leader node
      set_fact:
        drbd_leader: "{{ groups[target+'_drbd_nodes'][0] }}"
      tags:
        - check
        - first_time

    - name: Set fact for agents
      set_fact:
        drbd_nodes: "{{ groups[target+'_drbd_nodes'][1:] }}"
      tags:
        - check
        - first_time

#    - name: Check if drbd nodes are in cluster
#      shell: drbdmanage nodes -m 2>/dev/null | grep -c '^{{hostvars[item]["inventory_hostname_short"]}}'
#      with_items: "{{ drbd_nodes }}"
#      ignore_errors: yes
#      register: check
#      tags:
#        - check

#    - name: Leader node add agents in cluster
#      command: drbdmanage add-node {{ hostvars[item.item]['inventory_hostname_short'] }} {{ hostvars[item.item]['ansible_default_ipv4']['address'] }} -q
#      with_items: "{{ check.results }}"
#      register: add_node_command
#      until: add_node_command.rc == 0
#      retries: 5
#      when: inventory_hostname == drbd_leader and item.stdout == "0"
#      tags:
#        - check

    - name: Leader node add agents in cluster
      shell: drbdmanage add-node {{ hostvars[item]['inventory_hostname_short'] }} {{ hostvars[item]['ansible_default_ipv4']['address'] }} -q
      with_items: "{{ drbd_nodes }}"
      register: add_node_command
      when: inventory_hostname == drbd_leader
      tags:
        - check
        - first_time
