---
#- hosts: "{{ target + '_drbd_nodes' }}"
#  roles:
#     - common
#     - proxmox
   
#- hosts: "{{ target + '_drbd_nodes' }}"
#  roles:
#    - role: drbd_init

- hosts: "{{ target + '_drbd_nodes' }}"
#  serial: 1
  roles:
    - role: drbd_node_add

- hosts: "{{ target + '_drbd_nodes' }}"
  roles:
    - role: drbd_storage_plugin

