---
- name: Set fact for primary_node
  set_fact:
    drbd_primary_node: "{{ groups[target+'_drbd_nodes'][0] }}"
  tags:
    - drbd_cluster_init

- name: Set fact for agents
  set_fact:
    drbd_agents: "{{ groups[target+'_drbd_nodes'][1:] }}"
  tags:
    - drbd_cluster_init

- name: Create volume group for drbd
  lvg:
    vg: "{{ drbd_vg_name }}"
    pvs: "{{ drbd_disks }}"
  tags:
    - drbd_cluster_init

- name: Create volume
  lvol:
    vg: "{{ drbd_vg_name }}"
    lv: "{{ drbd_lv_name }}"
    size: "{{ drbd_volume_size }}"
  tags: 
    - drbd_cluster_init

- name: Convert volume to thin-pool
  command: "lvconvert --force --type thin-pool -y {{ drbd_vg_name }}/{{ drbd_lv_name }}"
  register: lvconvert
  failed_when: not "'LV drbdpool/drbdthinpool is already pool' in lvconvert.stderr" 
  tags: 
    - drbd_cluster_init

- name: Download DRBD9 package-signing-pubkey 
  apt_key: 
    url: "https://packages.linbit.com/package-signing-pubkey.asc" 
    state: present 
  tags:  
    - drbd_cluster_init
    - repo
 
- name: Add drbd9  repository from Linbit
  apt_repository: 
    repo: "deb https://packages.linbit.com/proxmox/ proxmox-4 drbd-9.0" 
    state: present 
  tags:  
    - drbd_cluster_init
    - repo

- name: Check Proxmox version 
  shell: "pveversion | cut -d '/' -f 2 | cut -d '.' -f 1" 
  register: pve_version 
  tags: 
    - check_pveversion


- name: Add no subscription repository
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve stretch pve-no-subscription"
    state: present
  when: pve_version.stdout == "5"
  tags:
    - drbd_cluster_init
    - repo
 
- name: Update repository packages
  apt: 
    update_cache: yes 
    state: latest 
  tags:  
    - drbd_cluster_init
    - repo

- name: Check if there is pve-kernel upgrade
  shell: apt list --upgradable 2>/dev/null | grep -c '^pve-kernel'
  register: kernel_upgrade
  ignore_errors: True

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
  when: kernel_upgrade.stdout == "1"

- name: Reboot
  shell: sleep 5; reboot
  async: 10
  poll: 0
  when: reboot | default(False) and kernel_upgrade.stdout == "1"
  tags:
    - reboot

- name: local action
  wait_for:
    delay: 15
    port: 22
    host: "{{ansible_default_ipv4['address']}}"
    timeout: 250
  delegate_to: localhost
  tags:
    - reboot

- name: Wait to start hosts
  wait_for:
    port: 8006
    state: started
  tags:
    - reboot

- name: Find kernel release
  command: "uname -r"
  register: release

- name: Install kernel-headers, drbdmanage-proxmox, drbd-dkms and their dependencies when Proxmox is version 5
  apt: 
    name:    
      - pve-headers-{{release.stdout}}
      - drbdmanage-proxmox
      - drbd-dkms
  when: pve_version.stdout == "5"
  tags:  
    - drbd_cluster_init
    - check_pveversion

- name: Install drbd-module, drbdmanage and their dependencies 
  apt: 
    name:    
      - drbdmanage-proxmox 
  when: pve_version.stdout == "4"
  tags:
    - drbd_cluster_init
    - check_pveversion

- name: Confirm that packages (drbd-utils, lvm2, drbdmanage) are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage
  tags:
    - drbd_cluster_init


