---
- name: Confirm that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage 

- name: Set fact
  set_fact:
    drbd_primary_node: "{{ groups[target+'_drbd_nodes'][0] }}"

- name: Set fact for agents
  set_fact:
    drbd_agents: "{{ groups[target+'_drbd_nodes'][1:] }}"

- name: Initiallizing Cluster only on master node
  command: drbdmanage init -q
  when: inventory_hostname == drbd_primary_node


- name: Add Nodes
  command: drbdmanage add-node {{ hostvars[item]['inventory_hostname_short'] }} {{ hostvars[item]['ansible_default_ipv4']["address"] }}
  with_items: "{{ drbd_agents }}"
  register: add_node_command
  until: add_node_command.rc == 0
  retries: 5
  when: inventory_hostname == drbd_primary_node

- name: How to Join
  command: drbdmanage howto-join -q {{ hostvars[item]['inventory_hostname_short'] }}
  with_items: "{{ drbd_agents }}"
  register: howto_join
  until: howto_join.rc == 0
  retries: 5
  when: inventory_hostname == drbd_primary_node and item in drbd_agents

- name: Restart drbdmanage
  command: drbdmanage restart -q

- name: Agents join in cluster
  command: "{{ item['stdout'] }}"
  with_items: "{{ hostvars[drbd_primary_node]['howto_join']['results'] }}"
  register: command_output
  until: command_output.rc == 0
  retries: 5
  when: inventory_hostname in drbd_agents and item['item'] == inventory_hostname

- name: Restart Drbdmanage at all
  command: drbdmanage restart -q
 
