---
- name: Confirm that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage 

- name: Set fact
  set_fact:
    drbd_primary_node: "{{ groups[target+'_drbd_nodes'][0] }}"

- name: Set fact for agents
  set_fact:
    drbd_agents: "{{ groups[target+'_drbd_nodes'][1:] }}"

- name: Initiallizing Cluster only on master node
  command: drbdmanage init -q
  when: inventory_hostname == drbd_primary_node


- name: Add Nodes
  shell: drbdmanage add-node {{ hostvars[item]['inventory_hostname_short'] }} {{ hostvars[item]['ansible_default_ipv4']["address"] }}
  with_items: drbd_agents 
  when: inventory_hostname == drbd_primary_node

- name: How to Join
  shell: drbdmanage howto-join -q {{ hostvars[item]['inventory_hostname_short'] }}
  with_items: drbd_agents
  register: howto_join
  when: inventory_hostname == drbd_primary_node and item in drbd_agents

- name: Debug How to join
  debug:
    var: hostvars[drbd_primary_node]['howto_join']['results']

- name: Agents join in cluster
  command: "{{ item['stdout'] }}"
  when: inventory_hostname in drbd_agents and item['item'] == inventory_hostname
  with_items: hostvars[drbd_primary_node]['howto_join']['results']

- name: Restart Drbdmanage at all
  command: drbdmanage restart -q
 
