---
- name: Confirm that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage 


- name: Initiallizing Cluster only on master node
  command: echo yes | drbdmanage init 
  when: inventory_hostname in groups['drbd_master']

- name: Add Nodes
  shell: drbdmanage add-node {{ ansible_hostname }} {{ ansible_default_ipv4["address"] }}
  when: ansible_host == master_node
  with_items: "{{ drbd_agents }}"

- name: How to Join
  shell: drbdmanage howto-join {{ ansible_hostname }}
  when: ansible_host != {{}}
  with_items: "{{ drbd_agents }}"
- name: Agents join in cluster
  shell:
