---
- name: Confirm that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage 


- name: Initiallizing Cluster only on master node
  command: echo yes | drbdmanage init 
  when: inventory_hostname in group_names['drbd_master']

- name: Add Nodes
  shell: drbdmanage add-node {{ ansible_hostname }} {{ ansible_default_ipv4["address"] }}
  when: ansible_host not in group_names['drbd_master']

- name: How to Join
  shell: drbdmanage howto-join {{ item }}
  with_items: groups_names['drbd_agents']
  register: results
  when: ansible_host in group_names['drbd_master']

- name: Agents join in cluster
  shell: {{ results }}
  when: ansible_host not in group_names['drbd_master']
  with_items: 
