---
- name: Confirm that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage 

- name: Set fact
  set_fact:
    drbd_primary_node: "{{ groups[target+'_drbd_nodes'][0] }}"

- name: Initiallizing Cluster only on master node
  command: drbdmanage init -q
  when: inventory_hostname == drbd_primary_node


- name: Add Nodes
  shell: drbdmanage add-node {{ hostvars[item]['inventory_hostname_short'] }} {{ hostvars[item]['ansible_default_ipv4']["address"] }}
  with_items:  groups[target+'_drbd_nodes'][1:] 
  when: inventory_hostname == drbd_primary_node

- name: How to Join
  shell: drbdmanage howto-join {{ hostvars[item]['inventory_hostname_short'] }}
  with_items: groups[target+'_drbd_nodes']
  register: howto_join
  when: inventory_hostname == drbd_primary_node and item != drbd_primary_node

- name: Agents join in cluster
  shell: "{{ item['stdout'] }}"
  when: inventory_hostname != drbd_primary_node 
  with_items: "{{ howto_join['results'] }}"

- name: Restart Drbdmanage at all
  command: drbdmanage restart -q
 
