---
- name: Confirm that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - drbd-utils
    - lvm2
    - drbdmanage 


- name: Initiallizing Cluster only on master node
  command: echo yes | drbdmanage init 
  when: inventory_hostname in groups['drbd_master']

- name: Add Nodes
  shell: drbdmanage add-node {{ ansible_hostname }} {{ ansible_default_ipv4["address"] }}
  when: not ansible_host in groups['drbd_master']

- name: How to Join
  shell: drbdmanage howto-join {{ ansible_hostname }}
  register: howto_join_result
  when: not ansible_host in groups['drbd_master']
  delegate_to: 

- name: Agents join in cluster
  shell:
