---
- name: Create volume group
  lvg:
    vg: "{{ drbd_vg_name }}"
    pvs: "{{ drbd_disks }}"

- name: Create volumes
  lvol:
    vg: "{{ drbd_vg_name }}"
    lv: "{{ drbd_lv_name }}"
    size: "{{ drbd_volume_size }}"

- name: Convert volume to thin-pool
  command: "lvconvert --type thin-pool -y --force {{ drbd_vg_name }}/{{ drbd_lv_name }}"
  register: result
  failed_when: not result.stderr.endswith("is already pool.")
 
