---
- name: Create volume group
  lvg:
    vg: drbdpool
    pvs: "{{ disks }}"

- name: Create volumes
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: "{{ volume_size }}"

- name: Convert volume to thin-pool
  command: "lvconvert --type thin-pool -y {{ vg_name }}/{{ lv_name }}"
  register: result
  failed_when: not result.stderr.endswith("is already pool.")
 
