---
- name: Create volume group
  lvg:
    vg: drbdpool
    pvs: 
      - { disk_1 }
      - { disk_2 }

- name: Create volumes
  lvol:
    vg: { vg_name }
    lv: { lv_name }
    size: { volume_size }

- name: Convert volume to thin-pool
  shell: "lvconvert --type thin-pool { vg_name }/{ vg_name }"

