---
- include: lvm.yml
- include: drbd_setup.yml
- include: drbd_cluster.yml
- include: storage_plugin.yml
  serial: 1
- name: Check drbd nodes status
  shell: drbdmanage list-nodes | grep {{ hostvars[item]['inventory_hostname_short'] }} | cut -d "|" -f 6
  with_items: "{{ groups[target+'_drbd_nodes'] }}"
  register: list_nodes_status
  tags:
    - status


