---
- name: Comment proxmox enterprise repository
  lineinfile:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^'
    line: '#deb https://enterprise.proxmox.com/debian stretch pve-enterprise'
    state: present

- name: Touch repo file
  shell: touch /etc/apt/sources.list.d/proxmox.list

- name: Add Proxmox repo
  lineinfile:
    dest: /etc/apt/sources.list.d/proxmox.list
    regexp: '^'
    line: 'deb http://download.proxmox.com/debian jessie pve-no-subscription'
- name: Updates
  apt:
    update_cache: yes
    upgrade: dist

- name: Set fact Proxmox master
  set_fact:
    proxmox_primary_node: "{{ groups[target+'_drbd_nodes'][0] }}"

- name: Set fact for Proxmox agents
  set_fact:
    proxmox_agents: "{{ groups[target+'_drbd_nodes'][1:] }}"
  
- name: Create a cluster on master
  shell: pvecm create my-cluster
  when: inventory_hostname_short in proxmox_primary_node
  ignore_errors: yes

- name: Nodes add themselves in cluster
  command: pvecm add {{ proxmox_primary_node }} -force
  register: result
  until: result.rc == 0
  retries: 5
  when: inventory_hostname in proxmox_agents
 
- name: Add drbdstorage configuration in a storage file
  template:
    src: storage.cfg.j2
    dest: /tmp/storage.cfg
    owner: root
    group: www-data
  when: inventory_hostname == proxmox_primary_node

- name: Copy storage.cfg to /etc/pve
  shell: cp /tmp/storage.cfg /etc/pve/ && rm /tmp/storage.cfg
  when: inventory_hostname == proxmox_primary_node
