---
- name: Set fact Proxmox master
  set_fact:
    proxmox_primary_node: "{{ groups[target+'_drbd_nodes'][0] }}"

- name: Set fact for Proxmox agents
  set_fact:
    proxmox_agents: "{{ groups[target+'_drbd_nodes'][1:] }}"
  
- name: Create a cluster on master
  shell: pvecm create my-cluster
  when: inventory_hostname_short in proxmox_primary_node

- name: Nodes add themselves in cluster
  shell: pvecm add {{ item }} --force
  with_items: "{{ hostvars[proxmox_primary_node]['ansible_hostname'] }}"
  when: inventory_hostname in proxmox_agents

- name: Add drbdstorage configuration in a storage file
  template:
    src: storage.j2
    dest: /etc/pve/storage  
  when: inventory_hostname == proxmox_primary_node

- name: Append content of storage file to storage.cfg
  shell: cat /etc/pve/storage >> /etc/pve/storage.cfg
  when: inventory_hostname == proxmox_primary_node

- name: Delete storage
  shell: rm /etc/pve/storage
  when: inventory_hostname == proxmox_primary_node
