---
- name: Cat public keys of hosts
  shell: cat /root/.ssh/id_rsa.pub
  register: public_key

- name: 
  authorized_key:
    user: root
    state: present
    key: "{{ hostvars[item]['public_key']['stdout'] }}"
  with_items: groups[target + '_drbd_nodes']
  when: item != inventory_hostname
  
  
