---
- name: Add hosts to /etc/hosts for resolve
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Cat public keys for root
  shell: cat /root/.ssh/id_rsa.pub
  register: root_public_key

- name: Cat public keys for hosts
  shell: cat /etc/ssh/ssh_host_rsa_key.pub
  register: host_public_key

- name: Add authorized keys for root user
  authorized_key:
    user: root
    state: present
    key: "{{ hostvars[item]['root_public_key']['stdout'] }}"
  with_items: "{{ groups[target+'_drbd_nodes'] }}"
  when: item != inventory_hostname

- name: Add host_public_key to known hosts
  known_hosts:
    name: "{{ item }}"
    path: /root/.ssh/known_hosts
    key: "{{ item }} {{ hostvars[item]['host_public_key']['stdout'] }}"
  with_items: "{{ groups[target+'_drbd_nodes'] }}"
  when: item != inventory_hostname
